pipeline {
    agent {
        node {
            label 'master'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                // ඔයාගේ GitHub Repository එකෙන් Python Code එක ගන්නවා
                git branch: 'main', url: 'https://github.com/Madhawakavindu/devops.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('python-jenkins-argocd') {
                        echo "Building Docker Image..."
                        // ඔයාගේ madhawa123 account එකට ගැළපෙන්න image එක build කරනවා
                        sh 'docker build -t madhawa123/python-app:latest .'
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    // Jenkins Credentials වල අපි හදපු 'docker-hub' ID එක පාවිච්චි කරනවා
                    withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'DOCKER_HUB_PASSWORD', usernameVariable: 'DOCKER_HUB_USERNAME')]) {
                        echo "Logging into Docker Hub..."
                        sh "echo \$DOCKER_HUB_PASSWORD | docker login -u \$DOCKER_HUB_USERNAME --password-stdin"
                        
                        echo "Pushing Image to Docker Hub..."
                        sh 'docker push madhawa123/python-app:latest'
                    }
                }
            }
        }
    }
}
